//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionApproval
    {
        public int Id { get; set; }
        public decimal NoOfHour { get; set; }
        public System.DateTime Date { get; set; }
        public string NameOfPerson { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<int> TimeOf { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
