//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string HomeStreet { get; set; }
        public Nullable<int> HomeCityId { get; set; }
        public Nullable<int> HomeCountryId { get; set; }
        public Nullable<int> CountryOfBirthId { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
        public Nullable<int> PlaceOfBirthId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<int> Ctizenship_Id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual CountryOfBirth CountryOfBirth { get; set; }
        public virtual Ctizenship Ctizenship { get; set; }
        public virtual HomeCity HomeCity { get; set; }
        public virtual HomeCountry HomeCountry { get; set; }
        public virtual PlaceOfBirth PlaceOfBirth { get; set; }
    }
}
