//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_events_lines
    {
        public int Id { get; set; }
        public int filenumber { get; set; }
        public System.DateTime dateFrom { get; set; }
        public byte @checked { get; set; }
        public Nullable<int> DocNum { get; set; }
    }
}
