//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Employees
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public string FirstName { get; set; }
        public string MidelName { get; set; }
        public string LastName { get; set; }
        public string KnownAs { get; set; }
        public Nullable<int> FileNumber { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> DepartementId { get; set; }
        public Nullable<int> TypeEmployeeId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Image { get; set; }
        public string BankCode { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> TimeShit { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public Nullable<int> EmployeeSubGroupId { get; set; }
        public Nullable<int> PayllorAreaId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public Nullable<int> NumberOfSickDays { get; set; }
        public Nullable<System.DateTime> StartSickDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Division { get; set; }
        public string SubDivision { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public string PromotionHistory { get; set; }
        public string IncreaseHistory { get; set; }
        public string BonusHistory { get; set; }
        public Nullable<int> CashOrBankId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<int> MedicalCoverId { get; set; }
        public Nullable<int> LiveCoverId { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> ReasonForEventId { get; set; }
        public string EmployementStatus { get; set; }
        public Nullable<decimal> SalaryCurrency { get; set; }
        public string AccountNo { get; set; }
        public string IDNo { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> License_Termination_Date { get; set; }
        public Nullable<System.DateTime> License_Expired_Date { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExiprationDate { get; set; }
        public Nullable<int> TypeOfHealthInsuranceId { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public Nullable<int> EducationStatusId { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<int> HealthInsuranceCompanyNameId { get; set; }
        public Nullable<int> PreviousYearsOfExperience { get; set; }
        public Nullable<int> TotalYearsOfExperience { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string HomeStreet { get; set; }
        public Nullable<int> HomeCityId { get; set; }
        public Nullable<int> HomeCountryId { get; set; }
        public Nullable<int> CountryOfBirthId { get; set; }
        public Nullable<int> PlaceOfBirthId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<decimal> MonthlyBasic { get; set; }
        public Nullable<decimal> AnnualBasic { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> SkillIncentive { get; set; }
        public Nullable<decimal> ExpensiveIncentive { get; set; }
        public Nullable<decimal> RegularityIncentive { get; set; }
        public Nullable<decimal> ConstValue { get; set; }
        public Nullable<decimal> DaysValue { get; set; }
        public Nullable<decimal> NumberOfVacation { get; set; }
        public Nullable<decimal> InMonthOrInYear { get; set; }
        public Nullable<decimal> VacationsBalance { get; set; }
        public Nullable<decimal> ManagementIncentive { get; set; }
        public Nullable<System.DateTime> VacationsBalanceDate { get; set; }
        public Nullable<int> DeferredType { get; set; }
        public Nullable<int> MaxDeferredVacation { get; set; }
        public Nullable<decimal> ProductivityDays { get; set; }
        public Nullable<decimal> ProductivityFixed { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> militaryStatusId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
