//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Fields
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string label { get; set; }
        public string html_or_html_partial { get; set; }
        public string html { get; set; }
        public string html_partial { get; set; }
        public string sql_or_collection { get; set; }
        public string sql { get; set; }
        public string collection { get; set; }
    }
}
