//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Menu
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string label { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> active { get; set; }
        public string link { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> line_num { get; set; }
    }
}
