//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Modules
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string Title { get; set; }
        public string url { get; set; }
        public string Header { get; set; }
        public string SQLSelect { get; set; }
    }
}
