//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Simple
    {
        public int Id { get; set; }
        public Nullable<int> simple_id { get; set; }
        public string table_name { get; set; }
        public string col_title { get; set; }
        public string Col_Name { get; set; }
        public string Col_Type { get; set; }
        public string col_class { get; set; }
        public Nullable<int> row_no { get; set; }
        public Nullable<bool> is_select { get; set; }
        public string table_select { get; set; }
        public string col_select_name { get; set; }
        public string col_select_value { get; set; }
        public string val_enum { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
