//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Shifts
    {
        public int Id { get; set; }
        public string ShiftName { get; set; }
        public int ShiftType { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> WeekendType { get; set; }
        public Nullable<int> WeekendDays { get; set; }
        public Nullable<int> M_W_D { get; set; }
        public Nullable<int> WeekelyHours { get; set; }
        public Nullable<int> MonthlyHours { get; set; }
        public Nullable<int> WeekelyDays { get; set; }
        public Nullable<int> MonthlyDays { get; set; }
        public Nullable<int> MonthlyLateHours { get; set; }
        public Nullable<int> MonthlyLateCount { get; set; }
        public Nullable<int> MonthlyLeaveHours { get; set; }
        public Nullable<int> MonthlyLeaveCount { get; set; }
        public Nullable<int> TimesId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
    }
}
