//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public Nullable<decimal> HoursNo { get; set; }
        public string Remarks { get; set; }
        public int AttendanceTypeId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> Leave { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<double> AttValue { get; set; }
        public Nullable<int> ShiftTempId { get; set; }
        public Nullable<byte> isStrict { get; set; }
        public Nullable<bool> @event { get; set; }
        public Nullable<int> weekend_cancel { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
