//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttTable
    {
        public int Id { get; set; }
        public int SalarySheetId { get; set; }
        public string Dayname { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
        public string abs { get; set; }
        public string att { get; set; }
        public Nullable<System.DateTime> dateDay { get; set; }
        public string errand { get; set; }
        public string lateHours { get; set; }
        public string leaveHours { get; set; }
        public string overTimeHour { get; set; }
        public string vacDay { get; set; }
        public string weekend { get; set; }
        public string special { get; set; }
    }
}
