//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicBayWork
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> PayScaleAreaId { get; set; }
        public Nullable<int> PayScaleTypeId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> AllowanceGroupId { get; set; }
        public Nullable<decimal> MonthlyBasic { get; set; }
        public Nullable<decimal> AnnualBasic { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> SkillIncentive { get; set; }
        public Nullable<decimal> ExpensiveLivingConditons { get; set; }
        public Nullable<decimal> RegularityIncentive { get; set; }
        public Nullable<decimal> IncentiveIncentiveForAbsence { get; set; }
        public Nullable<decimal> ConstValue { get; set; }
        public Nullable<decimal> NumberOfDays { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<bool> IsRegularityIncetive { get; set; }
        public Nullable<bool> IsNumberDaysOnly { get; set; }
        public Nullable<bool> IsConstValueOnly { get; set; }
        public Nullable<bool> AreNumberAndConstValue { get; set; }
        public Nullable<bool> IsSkillIncetive { get; set; }
        public Nullable<bool> IsExpesiveLiving { get; set; }
        public Nullable<decimal> NumberOfVacationInYear { get; set; }
        public Nullable<decimal> NumberOfVacationInManth { get; set; }
        public Nullable<decimal> NumberOfStageVacations { get; set; }
        public Nullable<int> SpareShiftId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<decimal> ManagementIncentive { get; set; }
        public Nullable<System.DateTime> VacationDeferredDate { get; set; }
        public Nullable<int> TempShiftId { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string dept { get; set; }
        public Nullable<int> MaxDeferredVacation { get; set; }
        public Nullable<decimal> ProductivityDays { get; set; }
        public Nullable<decimal> ProductivityFixed { get; set; }
        public Nullable<bool> isProMonthly { get; set; }
        public Nullable<bool> isProWeekly { get; set; }
        public Nullable<bool> withinSalary { get; set; }
        public string notes { get; set; }
    }
}
