//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicBayWorkLine
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> WageCodeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual WageCode WageCode { get; set; }
    }
}
