//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangelogDetail
    {
        public int Id { get; set; }
        public string columnName { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public int changeLogId { get; set; }
    
        public virtual changeLog changeLog { get; set; }
    }
}
