//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class changeLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public changeLog()
        {
            this.ChangelogDetails = new HashSet<ChangelogDetail>();
        }
    
        public int Id { get; set; }
        public string user { get; set; }
        public string IP { get; set; }
        public string crud { get; set; }
        public System.DateTime timeDone { get; set; }
        public string tableName { get; set; }
        public string singleValue { get; set; }
        public byte isSingleValue { get; set; }
        public string report { get; set; }
        public Nullable<byte> isMasterData { get; set; }
        public Nullable<System.DateTime> PostingDate1 { get; set; }
        public Nullable<System.DateTime> PostingDate2 { get; set; }
        public Nullable<System.TimeSpan> PostingTime1 { get; set; }
        public Nullable<System.TimeSpan> PostingTime2 { get; set; }
        public Nullable<double> Vacation { get; set; }
        public Nullable<double> Attendance { get; set; }
        public Nullable<decimal> TempShift { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> Leave { get; set; }
        public Nullable<double> Overtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangelogDetail> ChangelogDetails { get; set; }
    }
}
