//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> PaymentDeductionId { get; set; }
        public Nullable<int> RecurringOneTimeId { get; set; }
        public Nullable<int> TotalNet { get; set; }
        public int EmployeeId { get; set; }
        public string Remarkes { get; set; }
        public Nullable<double> DaysNumber { get; set; }
        public Nullable<int> Imposer { get; set; }
        public Nullable<int> Reason { get; set; }
    }
}
