//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AdditionApprovals = new HashSet<AdditionApproval>();
            this.Attachments = new HashSet<Attachment>();
            this.Attendances = new HashSet<Attendance>();
            this.BasicBayWorkLines = new HashSet<BasicBayWorkLine>();
            this.Payments = new HashSet<Payment>();
            this.SocialInsurances = new HashSet<SocialInsurance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public string FirstName { get; set; }
        public string MidelName { get; set; }
        public string LastName { get; set; }
        public string KnownAs { get; set; }
        public string FileNumber { get; set; }
        public Nullable<decimal> RatioWorkerProfits { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> DepartementId { get; set; }
        public Nullable<int> TypeEmployeeId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int PersonalId { get; set; }
        public int FinanceId { get; set; }
        public int AdministrationId { get; set; }
        public int AddressId { get; set; }
        public int GeneralId { get; set; }
        public string Image { get; set; }
        public int RemarkId { get; set; }
        public string BankCode { get; set; }
        public string BankCode2 { get; set; }
        public string color { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionApproval> AdditionApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicBayWorkLine> BasicBayWorkLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialInsurance> SocialInsurances { get; set; }
    }
}
