//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTransfer
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public int EmployeeId { get; set; }
        public int DeptId { get; set; }
        public int ShiftId { get; set; }
        public Nullable<double> TotalSalary { get; set; }
        public Nullable<double> Overtime { get; set; }
        public Nullable<double> Skill { get; set; }
        public Nullable<double> Expensive { get; set; }
        public Nullable<double> Management { get; set; }
        public Nullable<double> Regular { get; set; }
        public Nullable<double> ConstValue { get; set; }
        public Nullable<double> NumberOfDays { get; set; }
        public Nullable<bool> IsDays { get; set; }
        public Nullable<bool> IsConst { get; set; }
        public Nullable<bool> IsDaysAndConst { get; set; }
        public Nullable<double> VacationsNo { get; set; }
        public Nullable<System.DateTime> VacationsDate { get; set; }
        public Nullable<int> TempShiftId { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
