//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int Id { get; set; }
        public string PromotionHistory { get; set; }
        public string IncreaseHistory { get; set; }
        public string BonusHistory { get; set; }
        public string TransferHistory { get; set; }
        public int GrossOrNet { get; set; }
        public Nullable<int> CashOrBankId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<int> MedicalCoverId { get; set; }
        public Nullable<int> LiveCoverId { get; set; }
        public Nullable<int> OtherAllowanceId { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> ReasonForEventId { get; set; }
        public string EmployementStatus { get; set; }
        public Nullable<decimal> SalaryCurrency { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual CashOrBank CashOrBank { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual LiveCover LiveCover { get; set; }
        public virtual MedicalCover MedicalCover { get; set; }
        public virtual OtherAllowance OtherAllowance { get; set; }
        public virtual ReasonForEvent ReasonForEvent { get; set; }
    }
}
