//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General
    {
        public int Id { get; set; }
        public Nullable<int> IdIssuedByAuthorities { get; set; }
        public string IDNo { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> License_Termination_Date { get; set; }
        public Nullable<System.DateTime> License_Expired_Date { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExiprationDate { get; set; }
        public Nullable<int> PreviousYear { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public Nullable<int> TypeOfHealthInsuranceId { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public Nullable<int> EducationStatusId { get; set; }
        public string FirstNameOfSpouse { get; set; }
        public string LastNameOfSpouse { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> CrcNumber { get; set; }
        public string CrcState { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<int> HealthInsuranceCompanyNameId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<int> EducationalStatus_Id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual EducationalStatu EducationalStatu { get; set; }
        public virtual HealthInsuranceCompanyName HealthInsuranceCompanyName { get; set; }
        public virtual TypeOfHealthInsurance TypeOfHealthInsurance { get; set; }
    }
}
