//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrEntities1 : DbContext
    {
        public HrEntities1()
            : base("name=HrEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<AbsenceType> AbsenceTypes { get; set; }
        public virtual DbSet<Accessibility> Accessibilities { get; set; }
        public virtual DbSet<AClog> AClogs { get; set; }
        public virtual DbSet<AdditionApproval> AdditionApprovals { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<AK_Employees> AK_Employees { get; set; }
        public virtual DbSet<AK_events> AK_events { get; set; }
        public virtual DbSet<AK_events_lines> AK_events_lines { get; set; }
        public virtual DbSet<AK_Fields> AK_Fields { get; set; }
        public virtual DbSet<AK_Forms> AK_Forms { get; set; }
        public virtual DbSet<AK_Menu> AK_Menu { get; set; }
        public virtual DbSet<AK_Modules> AK_Modules { get; set; }
        public virtual DbSet<AK_Queries> AK_Queries { get; set; }
        public virtual DbSet<AK_Shifts> AK_Shifts { get; set; }
        public virtual DbSet<AK_Simple> AK_Simple { get; set; }
        public virtual DbSet<AK_work_periods> AK_work_periods { get; set; }
        public virtual DbSet<AllowanceGroup> AllowanceGroups { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<AttendanceType> AttendanceTypes { get; set; }
        public virtual DbSet<AttTable> AttTables { get; set; }
        public virtual DbSet<Authority> Authorities { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<BasicBayWorkLine> BasicBayWorkLines { get; set; }
        public virtual DbSet<BasicBayWork> BasicBayWorks { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<CashOrBank> CashOrBanks { get; set; }
        public virtual DbSet<changeLog> changeLogs { get; set; }
        public virtual DbSet<ChangelogDetail> ChangelogDetails { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<ContributionPeriod> ContributionPeriods { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<CountryOfBirth> CountryOfBirths { get; set; }
        public virtual DbSet<Ctizenship> Ctizenships { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DelayFromTo> DelayFromToes { get; set; }
        public virtual DbSet<Delay> Delays { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<DeptAssign> DeptAssigns { get; set; }
        public virtual DbSet<EducationalStatu> EducationalStatus { get; set; }
        public virtual DbSet<EmpAssign> EmpAssigns { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeSubGroup> EmployeeSubGroups { get; set; }
        public virtual DbSet<EmployeeTransfer> EmployeeTransfers { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Finance> Finances { get; set; }
        public virtual DbSet<General> Generals { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<HealthInsuranceCompanyName> HealthInsuranceCompanyNames { get; set; }
        public virtual DbSet<HomeCity> HomeCities { get; set; }
        public virtual DbSet<HomeCountry> HomeCountries { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<Incentive> Incentives { get; set; }
        public virtual DbSet<InsuranceAuthority> InsuranceAuthorities { get; set; }
        public virtual DbSet<InsuranceDetail> InsuranceDetails { get; set; }
        public virtual DbSet<InsurancePrecentage> InsurancePrecentages { get; set; }
        public virtual DbSet<InsuranceType> InsuranceTypes { get; set; }
        public virtual DbSet<JobHistory> JobHistories { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LiveCover> LiveCovers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MedicalCover> MedicalCovers { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<MSpeer_conflictdetectionconfigrequest> MSpeer_conflictdetectionconfigrequest { get; set; }
        public virtual DbSet<MSpeer_lsns> MSpeer_lsns { get; set; }
        public virtual DbSet<MyShift> MyShifts { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<OtherAllowance> OtherAllowances { get; set; }
        public virtual DbSet<PayllorArea> PayllorAreas { get; set; }
        public virtual DbSet<PaymentDeduction> PaymentDeductions { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PayScaleArea> PayScaleAreas { get; set; }
        public virtual DbSet<PayScaleType> PayScaleTypes { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<PlaceOfBirth> PlaceOfBirths { get; set; }
        public virtual DbSet<PostingPeriod> PostingPeriods { get; set; }
        public virtual DbSet<Productivity> Productivities { get; set; }
        public virtual DbSet<Profit> Profits { get; set; }
        public virtual DbSet<ReasonForEvent> ReasonForEvents { get; set; }
        public virtual DbSet<RecurringOneTime> RecurringOneTimes { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Remark> Remarks { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Roles2> Roles2 { get; set; }
        public virtual DbSet<SalarySheetGroup> SalarySheetGroups { get; set; }
        public virtual DbSet<SalarySheet> SalarySheets { get; set; }
        public virtual DbSet<Sanction> Sanctions { get; set; }
        public virtual DbSet<sanctions_reasons> sanctions_reasons { get; set; }
        public virtual DbSet<ShiftHoliday> ShiftHolidays { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<SocialInsurance> SocialInsurances { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysreplserver> sysreplservers { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TempShiftEntry> TempShiftEntries { get; set; }
        public virtual DbSet<tempshift> tempshifts { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<TypeEmployee> TypeEmployees { get; set; }
        public virtual DbSet<TypeOfHealthInsurance> TypeOfHealthInsurances { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<users_Authorities> users_Authorities { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<WageCode> WageCodes { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<LeaveFromTo> LeaveFromToes { get; set; }
        public virtual DbSet<MSpeer_conflictdetectionconfigresponse> MSpeer_conflictdetectionconfigresponse { get; set; }
        public virtual DbSet<MSpeer_originatorid_history> MSpeer_originatorid_history { get; set; }
        public virtual DbSet<MSpeer_request> MSpeer_request { get; set; }
        public virtual DbSet<MSpeer_response> MSpeer_response { get; set; }
        public virtual DbSet<MSpeer_topologyrequest> MSpeer_topologyrequest { get; set; }
        public virtual DbSet<MSpeer_topologyresponse> MSpeer_topologyresponse { get; set; }
        public virtual DbSet<MSpub_identity_range> MSpub_identity_range { get; set; }
        public virtual DbSet<SalarySheet1> SalarySheets1 { get; set; }
        public virtual DbSet<sysarticlecolumn> sysarticlecolumns { get; set; }
        public virtual DbSet<sysarticle> sysarticles { get; set; }
        public virtual DbSet<sysarticleupdate> sysarticleupdates { get; set; }
        public virtual DbSet<syspublication> syspublications { get; set; }
        public virtual DbSet<sysschemaarticle> sysschemaarticles { get; set; }
        public virtual DbSet<syssubscription> syssubscriptions { get; set; }
        public virtual DbSet<systranschema> systranschemas { get; set; }
        public virtual DbSet<Users2> Users2 { get; set; }
        public virtual DbSet<XReligion> XReligions { get; set; }
    }
}
