//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incentive
    {
        public int Id { get; set; }
        public string Describe { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> Taxable { get; set; }
        public Nullable<int> TypeOfValue { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> PerformanceEvaluation { get; set; }
    
        public virtual JobTitle JobTitle { get; set; }
    }
}
