//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePrecentage
    {
        public int Id { get; set; }
        public Nullable<decimal> ofFixedSalartForEmployeeContrribution { get; set; }
        public Nullable<decimal> ofVariableSalartForEmployeeContrribution { get; set; }
        public Nullable<decimal> ofFixedSalartForCompanyContrribution { get; set; }
        public Nullable<decimal> ofVariableSalartForCompanyContrribution { get; set; }
    }
}
