//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceDetail
    {
        public int Id { get; set; }
        public Nullable<decimal> EmployeeFixedSalary { get; set; }
        public Nullable<decimal> CompanyFixedSalary { get; set; }
        public Nullable<decimal> EmplyeeVariableSalary { get; set; }
        public Nullable<decimal> CompanyVariableSalary { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> InsuranceAuthorityId { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
