//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyShift
    {
        public int Id { get; set; }
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        public Nullable<int> ActiveDisactive { get; set; }
        public Nullable<int> WeekendFromDay { get; set; }
        public Nullable<int> WeekendToDay { get; set; }
        public Nullable<int> EmploymentPercent { get; set; }
        public Nullable<double> DailyHours { get; set; }
        public Nullable<int> WeekelyDays { get; set; }
        public Nullable<int> WeekelyHours { get; set; }
        public Nullable<int> MonthlyHours { get; set; }
        public Nullable<int> MonthlyLeaveDays { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string LateArrive { get; set; }
        public string EarlyLeave { get; set; }
        public string EarlyArrive { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public int NoOfShifts { get; set; }
        public Nullable<int> Shift2 { get; set; }
        public Nullable<int> Shift3 { get; set; }
        public Nullable<int> ReplaceShiftEvery { get; set; }
        public Nullable<bool> IsFullTime { get; set; }
        public Nullable<bool> IsWeekend { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<bool> IsOneShift { get; set; }
        public Nullable<bool> IsTwoShift { get; set; }
        public Nullable<bool> IsThreeShift { get; set; }
        public Nullable<int> GroupShifts { get; set; }
        public Nullable<int> SearchOption { get; set; }
    }
}
