//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> PaymentDeductionId { get; set; }
        public Nullable<int> WageCodeId { get; set; }
        public Nullable<int> RecurringOneTimeId { get; set; }
        public Nullable<int> TotalNet { get; set; }
        public int EmployeeId { get; set; }
        public string Remarkes { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<double> DaysNumber { get; set; }
        public Nullable<int> DeductionId { get; set; }
        public Nullable<int> Imposer { get; set; }
        public Nullable<int> reason { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentDeduction PaymentDeduction { get; set; }
        public virtual RecurringOneTime RecurringOneTime { get; set; }
        public virtual WageCode WageCode { get; set; }
    }
}
