//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> TimeShit { get; set; }
        public Nullable<int> EmployeeGroupId { get; set; }
        public Nullable<int> EmployeeSubGroupId { get; set; }
        public Nullable<int> PayllorAreaId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public Nullable<int> NumberOfSickDays { get; set; }
        public Nullable<System.DateTime> StartSickDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string PersonalArea { get; set; }
        public string PersonalSubArea { get; set; }
        public string Division { get; set; }
        public string SubDivision { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> OffDate { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> XReligionId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string TerminationReason { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual EmployeeGroup EmployeeGroup { get; set; }
        public virtual EmployeeSubGroup EmployeeSubGroup { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual PayllorArea PayllorArea { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Status Status { get; set; }
    }
}
