//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles2
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int Vacation { get; set; }
        public int Mission { get; set; }
        public int Attendance { get; set; }
        public int OverTime { get; set; }
        public int Salary { get; set; }
        public int ClosingPeriod { get; set; }
        public int FingerMachine { get; set; }
        public int Reports_Abs { get; set; }
        public int Reports_Salary_Details { get; set; }
        public int Logs { get; set; }
        public int TempShifts { get; set; }
        public int Employee { get; set; }
        public int BasicBayWorks { get; set; }
        public Nullable<int> Insurance { get; set; }
    }
}
