//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Employee { get; set; }
        public int Basic_Bay_Work { get; set; }
        public int Social_Insurance { get; set; }
        public int Shift { get; set; }
        public int Attendance { get; set; }
        public int Absence { get; set; }
        public int Salary_Sheet { get; set; }
        public int Import_Master_Data { get; set; }
        public int Import_Monthly_Attendances { get; set; }
        public int Payment { get; set; }
        public int Additional_Approval { get; set; }
        public int Create_New_User { get; set; }
        public int Settings { get; set; }
        public int role1 { get; set; }
        public int Delay { get; set; }
        public int Sanction { get; set; }
        public int Vacation { get; set; }
        public int Taxes { get; set; }
        public int OverTime { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
