//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySheet1
    {
        public int Id { get; set; }
        public int FileNumber { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Attendance { get; set; }
        public Nullable<decimal> Vacation { get; set; }
        public Nullable<decimal> Abcence { get; set; }
        public Nullable<decimal> SalaryMonth { get; set; }
        public Nullable<decimal> DaysValue { get; set; }
        public Nullable<decimal> RegularityIncentive { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> SkillIncentive { get; set; }
        public Nullable<decimal> ExpensiveIncetive { get; set; }
        public Nullable<decimal> Total1 { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> Loans { get; set; }
        public Nullable<decimal> ManagmentIncetive { get; set; }
        public Nullable<decimal> Sanctions_Delays { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> Clothes { get; set; }
        public Nullable<decimal> Delays { get; set; }
        public Nullable<decimal> Total2 { get; set; }
        public Nullable<decimal> Total3 { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string User { get; set; }
        public string Days { get; set; }
        public Nullable<double> attSum { get; set; }
        public Nullable<double> absSum { get; set; }
        public Nullable<double> vacSum { get; set; }
        public Nullable<double> errandSum { get; set; }
        public Nullable<double> sepcialSum { get; set; }
        public Nullable<double> overtimeSum { get; set; }
        public Nullable<double> lateSum { get; set; }
        public Nullable<double> leaveSum { get; set; }
        public Nullable<double> deductionSum { get; set; }
    }
}
