//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySheet
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> NoOfDateMorning { get; set; }
        public Nullable<decimal> NoOfDateVacation { get; set; }
        public Nullable<decimal> SalaryManth { get; set; }
        public Nullable<decimal> NumberOfDays { get; set; }
        public Nullable<decimal> RegularityIncentive { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> OvertimeRate { get; set; }
        public Nullable<decimal> OvertimeValue { get; set; }
        public Nullable<decimal> SkillIncentive { get; set; }
        public Nullable<decimal> expensiveLivingConditons { get; set; }
        public Nullable<decimal> OutstandingSentence { get; set; }
        public Nullable<decimal> BasicInsurance { get; set; }
        public Nullable<decimal> VariableInsurance { get; set; }
        public Nullable<decimal> H_Basic { get; set; }
        public Nullable<decimal> H_Variable { get; set; }
        public Nullable<decimal> Loans { get; set; }
        public Nullable<decimal> AbsenceDiscount { get; set; }
        public Nullable<decimal> SanctionsDiscount { get; set; }
        public Nullable<decimal> DiscountDelays { get; set; }
        public Nullable<decimal> Candied { get; set; }
        public Nullable<decimal> InterruptedSentence { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<decimal> NotToBeAbsent { get; set; }
        public string Date { get; set; }
        public int SalarySheetGroupsId { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public string FileNo { get; set; }
        public Nullable<decimal> PrivateInsurancePremium { get; set; }
        public Nullable<decimal> Reward { get; set; }
        public Nullable<decimal> HealthInsuranceStatement { get; set; }
        public Nullable<decimal> AnnualLeaveAllowance { get; set; }
        public Nullable<decimal> ExtraIncentives { get; set; }
        public Nullable<decimal> ExtraBonuses { get; set; }
        public Nullable<decimal> ExtraBonusesAddToBasicSalary { get; set; }
    
        public virtual SalarySheetGroup SalarySheetGroup { get; set; }
    }
}
