//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanction
    {
        public int Id { get; set; }
        public int ShiftId { get; set; }
        public string Shift_Name { get; set; }
        public int Shift_Id { get; set; }
        public string First_Delay { get; set; }
        public string Second_Delay { get; set; }
        public string Third_Delay { get; set; }
        public decimal DaliyWorkHour { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
    
        public virtual Shift Shift { get; set; }
    }
}
