//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialInsurance
    {
        public int Id { get; set; }
        public System.DateTime DateOfEnrollment { get; set; }
        public Nullable<decimal> ofFixedSalartForEmployeeContrribution1 { get; set; }
        public Nullable<decimal> ofVariableSalartForEmployeeContrribution1 { get; set; }
        public Nullable<decimal> EmployeeFixedSalary { get; set; }
        public Nullable<decimal> ofFixedSalartForCompanyContrribution1 { get; set; }
        public Nullable<decimal> ofVariableSalartForCompanyContrribution1 { get; set; }
        public Nullable<decimal> CompanyFixedSalary { get; set; }
        public string Advance { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> ContributionPeriodId { get; set; }
        public Nullable<int> InsuranceTypeId { get; set; }
        public string ValidUpdto { get; set; }
        public Nullable<decimal> ofFixedSalartForEmployeeContrribution2 { get; set; }
        public Nullable<decimal> ofVariableSalartForEmployeeContrribution2 { get; set; }
        public Nullable<decimal> EmplyeeVariableSalary { get; set; }
        public Nullable<decimal> ofFixedSalartForCompanyContrribution2 { get; set; }
        public Nullable<decimal> ofVariableSalartForCompanyContrribution2 { get; set; }
        public Nullable<decimal> CompanyVariableSalary { get; set; }
        public Nullable<int> IsCreated { get; set; }
        public Nullable<int> IsUpdated { get; set; }
    
        public virtual ContributionPeriod ContributionPeriod { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
    }
}
