//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempshift
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string ShiftFrom { get; set; }
        public string ShiftTo { get; set; }
        public Nullable<double> ShiftHours { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<int> DelayId { get; set; }
        public Nullable<int> LeaveId { get; set; }
        public Nullable<int> shift2 { get; set; }
        public Nullable<int> shift3 { get; set; }
        public string shiftName { get; set; }
    }
}
