//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users2
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Image { get; set; }
        public Nullable<short> All { get; set; }
        public Nullable<short> Departments { get; set; }
        public Nullable<short> Employees { get; set; }
        public Nullable<bool> HaveApprove { get; set; }
        public Nullable<int> ApproveId { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> StageClass { get; set; }
        public string ip_restrict { get; set; }
        public string active { get; set; }
    }
}
